Class {
	#name : #ChartStyleOptionInterface,
	#superclass : #Object,
	#category : #'D3SCharts-Options'
}

{ #category : #printing }
ChartStyleOptionInterface >> printHeight [

	self subclassResponsibility
]

{ #category : #printing }
ChartStyleOptionInterface >> printPadding [

	self subclassResponsibility
]

{ #category : #printing }
ChartStyleOptionInterface >> printWidth [

	self subclassResponsibility
]
